---
version: 3.0.1
slug: digo_ota_provider
name: DIGO OTA Provider
description: DIGO OTA Provider for supporting OTA DIGO devices on Home Assistant.
# url: >-
#   https://github.com/home-assistant/addons/tree/master/matter_server
arch:
  - aarch64
  - amd64
hassio_api: true
# IPC is only used within the Add-on
host_ipc: false
host_network: true
host_dbus: true
init: false
uart: true
options:
  log_level: info
  matter_server: localhost:5580
schema:
  log_level: list(debug|info|warning|error|critical)
ports:
  5580/tcp: null
# stage: experimental
startup: services
